### ISSUE TITLE
Add more examples :cow:

### ISSUE THREAD

**Issue by octosteve** [learn-co-curriculum/intro-to-js-and-jasmine#1]
Include Examples for functions, prototypes, conditionals, and scope(?maybe?) :cow:

**Comment by AnnJohn** [comment]
Since this hasn't been looked at for a while, but the suggestion is pretty helpful to improve the readme so will label icebox.

**Comment by AnnJohn** [comment]
@vicfriedman can this one be closed?

**Comment by victhevenot** [comment]
let's close this - students don't know what all of those things are (functions, scope, conditionals) in JavaScript yet
