### ISSUE TITLE
Error on running learn / learn -b on intro to JS labs

### ISSUE THREAD

**Issue by michaelsimon** [learn-co-curriculum/intro-to-js-and-jasmine#19]
When I am running learn or learn -b on Intro to JS labs, I get  the following error in my CLI
Installing missing dependency phantomjs...
Error: An unsatisfied requirement failed this build.

When running learn alone, no other output displays. When running learn -b, this error displays but then the browser opens and Jasmine seems to function normally.

This also seems to automatically trigger local tests to pass even though they have not.

I've tried uninstalling and reinstalling node and phantomjs ("npm install -g phantomjs" and "npm install -g phantomjs-prebuilt"). Can't install via Homebrew (running OSX 10.11).

Not sure how concerned I should be. Conversed with Brian Hollan on "Ask A Question" on Learn this evening, see that convo for more details and command output.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by michaelsimon** [comment]
Hi @pletcher, I am using Local environment. OS X 10.11. I put stack traces in my question on Learn.co, can you reference there? 

Update: added below

**Comment by michaelsimon** [comment]
BHOLLAN SAID AN HOUR AGO
Hi Michael! I'm Brian
MICHAELSIMON SAID AN HOUR AGO
I also uninstalled and reinstalled node

MICHAELSIMON SAID AN HOUR AGO
hi Brian

BHOLLAN SAID AN HOUR AGO
ok, so have you tried installing phantomjs independently?
MICHAELSIMON SAID AN HOUR AGO
i've done npm install -g phantomjs-prebuilt

MICHAELSIMON SAID AN HOUR AGO
and sudo'd it as well

BHOLLAN SAID AN HOUR AGO
Also, are you running on the IDE or a local environment?
MICHAELSIMON SAID AN HOUR AGO
and it seems like it installed ok

MICHAELSIMON SAID AN HOUR AGO
local

BHOLLAN SAID AN HOUR AGO
what OS?
MICHAELSIMON SAID AN HOUR AGO
OS X 10.11 el capitan

BHOLLAN SAID AN HOUR AGO
Can you paste in everything from the console when you run learn?
MICHAELSIMON SAID AN HOUR AGO
[21:21:58](master) intro-to-js-and-jasmine-v-000
// ♥ learn
Installing missing dependency phantomjs...
Error: An unsatisfied requirement failed this build.

BHOLLAN SAID AN HOUR AGO
So when you run phantomjs --version, what does it say?
MICHAELSIMON SAID AN HOUR AGO
[21:22:27](master) intro-to-js-and-jasmine-v-000
// ♥ phantomjs --version
-bash: phantomjs: command not found

MICHAELSIMON SAID AN HOUR AGO
if I do npm -g list

MICHAELSIMON SAID AN HOUR AGO
I have...

MICHAELSIMON SAID AN HOUR AGO
/usr/local/Cellar/node/5.2.0/libexec/npm/lib
└─┬ phantomjs-prebuilt@2.1.7
  ├─┬ extract-zip@1.5.0
  │ ├─┬ concat-stream@1.5.0
  │ │ ├── inherits@2.0.1
  │ │ ├─┬ readable-stream@2.0.6
  │ │ │ ├── core-util-is@1.0.2
  │ │ │ ├── isarray@1.0.0
  │ │ │ ├── process-nextick-args@1.0.7
  │ │ │ ├── string_decoder@0.10.31
  │ │ │ └── util-deprecate@1.0.2
  │ │ └── typedarray@0.0.6
  │ ├── debug@0.7.4
  │ ├─┬ mkdirp@0.5.0
  │ │ └── minimist@0.0.8
  │ └─┬ yauzl@2.4.1
  │   └─┬ fd-slicer@1.0.1
  │     └── pend@1.2.0

BHOLLAN SAID AN HOUR AGO
looking...
MICHAELSIMON SAID AN HOUR AGO
ok thanks

BHOLLAN SAID AN HOUR AGO
It's possible that the npm package changed names since this lesson was built.

BHOLLAN SAID AN HOUR AGO
I can't find any reference to a date of when it changed from phantomjs to phantomjs-prebuilt

BHOLLAN SAID AN HOUR AGO
https://www.npmjs.com/package/phantomjs

BHOLLAN SAID AN HOUR AGO
Do you want to try installing it manually? It doesn't look too bad.

BHOLLAN SAID AN HOUR AGO
I'm not 100% sure that will fix it, but that seems worth a try at least.
MICHAELSIMON SAID AN HOUR AGO
yeah i've tried uninstall reinstall, i just also did npm install phantomjs within the lab folder and it put the node_modules in my lab folder but running learn still gives me the error

MICHAELSIMON SAID AN HOUR AGO
[21:28:43](master) intro-to-js-and-jasmine-v-000
// ♥ npm install phantomjs

## npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'

> phantomjs@2.1.7 install /Users/mhsimon/Development/code/intro-to-js-and-jasmine-v-000/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/h8/bsq9_lfn5s1778jztg3wclv00000gp/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/mhsimon/Development/code/intro-to-js-and-jasmine-v-000/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/h8/bsq9_lfn5s1778jztg3wclv00000gp/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1467769126913/phantomjs-2.1.1-macosx -> /Users/mhsimon/Development/code/intro-to-js-and-jasmine-v-000/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/mhsimon/Development/code/intro-to-js-and-jasmine-v-000/node_modules/phantomjs/lib/phantom/bin/phantomjs
phantomjs@2.1.7 node_modules/phantomjs
├── progress@1.1.8
├── kew@0.7.0
├── request-progress@2.0.1 (throttleit@1.0.0)
├── which@1.2.10 (isexe@1.1.2)
├── hasha@2.2.0 (is-stream@1.1.0, pinkie-promise@2.0.1)
├── extract-zip@1.5.0 (debug@0.7.4, yauzl@2.4.1, mkdirp@0.5.0, concat-stream@1.5.0)
├── fs-extra@0.26.7 (path-is-absolute@1.0.0, klaw@1.3.0, graceful-fs@4.1.4, jsonfile@2.3.1, rimraf@2.5.3)
└── request@2.67.0 (tunnel-agent@0.4.3, aws-sign2@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@5.2.0, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, bl@1.0.3, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
[21:38:47](master) intro-to-js-and-jasmine-v-000
// ♥ learn
Installing missing dependency phantomjs...
Error: An unsatisfied requirement failed this build.

BHOLLAN SAID AN HOUR AGO
hmmm
MICHAELSIMON SAID AN HOUR AGO
i've spent a few hrs on this myself, can't tell if it has something to do with PATH variable or not

BHOLLAN SAID 24 MINUTES AGO
Michael, I'm really confused. Is this your pull request?

BHOLLAN SAID 24 MINUTES AGO
https://github.com/learn-co-students/intro-to-js-and-jasmine-v-000/pull/113

BHOLLAN SAID 23 MINUTES AGO
Did you get it working? What did it?
MICHAELSIMON SAID 23 MINUTES AGO
yes, it works if i do learn -b, it opens in a browser

MICHAELSIMON SAID 22 MINUTES AGO
but when I do learn or learn -b and before the browser opens, i get that error

BHOLLAN SAID 22 MINUTES AGO
So it's just running with errors?
MICHAELSIMON SAID 22 MINUTES AGO
it seems to be

MICHAELSIMON SAID 22 MINUTES AGO
it doesn't give me output in cli

BHOLLAN SAID 21 MINUTES AGO
huh. ok. Can you put an issue into the curriculum about this? The output should be in the browser, but you shouldn't be getting this error. Be as specific as you can and be sure to state that you're running locally and not on the IDE
MICHAELSIMON SAID 20 MINUTES AGO
ok email support@learn.co?

BHOLLAN SAID 18 MINUTES AGO
No, click the little flag in the lesson. It should take you to a 'new issue' page on the github repo in the curriculum
MICHAELSIMON SAID 17 MINUTES AGO
ok, it doesn't seem to be specific to just this one JS lab (so far)

BHOLLAN SAID 16 MINUTES AGO
Right, angular has a better test suite called Protractor, but for vanilla JS, our current testing setup is Jasmine in the browser

BHOLLAN SAID 15 MINUTES AGO
But it shouldn't give you errors when it runs without a problem.
MICHAELSIMON SAID 15 MINUTES AGO
ok will do, thanks Brian

BHOLLAN SAID 15 MINUTES AGO
My pleasure
~~ This question has been resolved ~~

**Comment by pletcher** [comment]
Hm, this is very strange. I've pulled down your PR and can't replicate the error.

Why doesn't installing phantom with Homebrew work?

**Comment by michaelsimon** [comment]
Thanks, Michael

**Comment by michaelsimon** [comment]
It looks like there is a known issue on Homebrew and OS X 10.11 with phantomjs
https://github.com/Homebrew/legacy-homebrew/issues/42249

I finally got it working by adding a new PATH variable in my .bash_profile file to point to the phantomjs bin.

I guess it was an environment issue.

**Comment by pletcher** [comment]
I've removed `learn -b` and made the tests runnable pretty much anywhere. Fingers crossed!
